languageCode = "en-uk"
title = "Operating Systems and C"
#baseurl = "https://brainbaking.com/"

theme = "hugo-theme-learn"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-45748221-1"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    showBorder = true
    highlight = true
    highlightStyle = "paraiso-dark"
    highlightLanguages = ["cs", "cpp", "scheme", "python", "java", "scala", "javascript", "llvm"]
    font = "Source Serif Pro"

    copyright = "No <i class='fa fa-copyright'></i> reserved - sharing is caring."

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Jo Vliegen, Wouter Groeneveld"
  email = "<i>fname</i>.<i>lname</i>A T<i>kuleuven.be</i>"
