languageCode = "en-uk"
title = "Operating Systems and C"

baseurl = "https://kuleuven-diepenbeek.github.io/osc-course/"
# fix for subdir baseurl, see https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

theme = "hugo-theme-learn"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodefences = true

# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

# for new Hugo 0.6x, markup changed to CommonMark.
[markup]
	defaultMarkdownHandler = "blackfriday"
	[markup.blackFriday]
		skipHTML = false

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Wouter Groeneveld and Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>kuleuven.be</i>"

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> Toledo"
identifier = "tol"
url = "TODO"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> ECTS Sheet"
identifier = "stud"
url = "https://uhintra03.uhasselt.be/studiegidswww/opleidingsonderdeel.aspx?a=2019&i=4082&n=4&t=01"
weight = 1
