languageCode = "en-uk"
title = "Operating Systems and C"
#baseurl = "http://192.168.1.184/osc"

theme = "hugo-theme-learn"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodefences = true

# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Wouter Groeneveld and Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>kuleuven.be</i>"

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> Toledo"
identifier = "tol"
url = "TODO"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> ECTS Sheet"
identifier = "stud"
url = "https://uhintra03.uhasselt.be/studiegidswww/opleidingsonderdeel.aspx?a=2019&i=4082&n=4&t=01"
weight = 1
