languageCode = "en-us"
title = "Brain Baking"
baseurl = "https://brainbaking.com/"
theme = "minimal"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-45748221-1"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true

[taxonomies]
    tag = "tags"

[params]
    description = "Freshly baked thought"
    # see single.html, DisqusShortname also needed
    disableComments = true
    accent = "purple"
    showBorder = true
    twitter = "woutergroenev"
    backgroundColor = "white"
    highlight = true
    highlightStyle = "paraiso-dark"
    highlightLanguages = ["cs", "cpp", "scheme", "python", "java", "scala", "javascript", "llvm"]
    font = "Source Serif Pro"
    copyright = "No <i class='fa fa-copyright'></i> reserved - sharing is caring. <i class='fa fa-github'></i> <a href='https://github.com/wgroeneveld/brainbaking/'>Hack away</a>! <i class='fa fa-lightbulb-o'></i> <a href='/'>Brain Baking</a>"

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"
